### ISSUE TITLE
Error: corrupted input

### ISSUE THREAD

**Issue by dongli** [nmrugg/LZMA-JS#54]
I have transferred xz file into JS using `XMLHttpRequest`. The content type of response is `application/x-xz`, and I checked `response` content which seems complete. Then I use `LZMA.decomporess(request.response, ...)` and got `corrupted input` error. What is wrong in my case? Thanks in advance.

**Comment by addaleax** [comment]
LZMA-JS doesn’t support xz files, just the raw `lzma` format. Your best option is probably to provide the data in `lzma` format on the server side, if that’s possible.

**Comment by jakirkham** [comment]
Also fun fact in case anyone runs into this. Python converts to `xz` format by default when using `lzma.compress`. To fix this one must pass `lzma.FORMAT_ALONE` to the `format` argument to get data compressed in a way that LZMA-JS can use. Ran into this when compressing a gob of binary data in Python that needed to be decompressed by JavaScript for use in a plot.

**Comment by nwtgck** [comment]
I got "Corrupt input data" too.

## Confirmation

Here is my confirmation code process.

First, I type the following command found at [LZMA-JS Advanced Demo](http://cdn.jwebsocket.org/lzma-js/1.3.7/demos/advanced_demo.html).
```bash
$ echo "Hello, world." | lzma -3 | hexdump -C | cut -c9-60
  5d 00 00 40 00 ff ff ff  ff ff ff ff ff 00 24 19  
  49 86 e7 d6 3b 91 a7 78  42 d7 c2 fe e2 25 55 d4  
  ff ff eb 7b 00 00   
```

Then, I use the following Python script.

```py
import lzma

# The output of `echo "Hello, world." | lzma -3 | hexdump -C | cut -c9-60`
s = b'\x5d\x00\x00\x40\x00\xff\xff\xff\xff\xff\xff\xff\xff\x00\x24\x19\x49\x86\xe7\xd6\x3b\x91\xa7\x78\x42\xd7\xc2\xfe\xe2\x25\x55\xd4\xff\xff\xeb\x7b\x00\x00'

lzma.LZMADecompressor().decompress(s)
# => b'Hello, world.\n'

```

As you can see, I can decompress successfully.

However, I tried on the result is from [LZMA-JS Advanced Demo](http://cdn.jwebsocket.org/lzma-js/1.3.7/demos/advanced_demo.html)

```
5d 00 00 01 00 0d 00 00 00 00 00 00 00 00 24 19
49 98 6f 16 02 8c e8 e6 5b b1 47 f3 de f4 89 ff
ff 30 44 00 00
```



```py
import lzma

# The output of LZMA-JS Advanced Demo
s = b'\x5d\x00\x00\x01\x00\x0d\x00\x00\x00\x00\x00\x00\x00\x00\x24\x19\x49\x98\x6f\x16\x02\x8c\xe8\xe6\x5b\xb1\x47\xf3\xde\xf4\x89\xff\xff\x30\x44\x00\x00'

lzma.LZMADecompressor().decompress(s)
# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
# _lzma.LZMAError: Corrupt input data
```

As you can see I got "Corrupt input data." Maybe my usage is wrong, but I think LZMA-JS probably has a problem.

**Comment by markb-trustifi** [comment]
It looks like there is an error in function `$SetDecoderProperties`, file `lzma_worker.js`:
```js
for (i = 0; i < 4; ++i) {
   dictionarySize += (properties[1 + i] & 255) << i * 8;
}
```

Because of the `<<i*8` the dictionarySize goes to enormous values.

**Comment by sindre-nistad** [comment]
Are there any known workarounds for @dongli's, and @nwtgck's corrupted data issue?

**Comment by mauron85** [comment]
Same problem. Testing with xz raw:

```
# compress into raw format
echo "hello" | xz -c --lzma1=lc=3,lp=0,pb=2 --format=raw > qr.xz

# test decode with xz - prints hello
cat qr.xz | xz -d --lzma1=lc=3,lp=0,pb=2 --format=raw

```

Try to decode with LZMA-JS

```
const fs = require("fs");
const LZMA = require("lzma");

const path = 'qr.xz';
const file = fs.readFileSync(path);
const byteArray = new Uint8Array(file);
const decomp = LZMA.decompress(byteArray);
console.log(decomp);
```

Fails with exception:

```
➜  RAMDisk node decomp.js
/Volumes/RAMDisk/node_modules/lzma/src/lzma_worker.js:313
            throw new Error("corrupted input");
            ^

Error: corrupted input
    at $init_0 (/Volumes/RAMDisk/node_modules/lzma/src/lzma_worker.js:313:19)
    at $LZMAByteArrayDecompressor (/Volumes/RAMDisk/node_modules/lzma/src/lzma_worker.js:344:9)
    at Object.decompress (/Volumes/RAMDisk/node_modules/lzma/src/lzma_worker.js:2554:29)
    at Object.<anonymous> (/Volumes/RAMDisk/decomp.js:7:21)
```

Same problem occurs, when I try to decompress file created with LZMA-JS with xz:

```
cat qr.xz | xz -d --lzma1=lc=3,lp=0,pb=2 --format=raw

xz: (stdin): Compressed data is corrupt
```

**Comment by xseman** [comment]
@mauron85 I'm having same issue, have you figured the problem?

**Comment by mauron85** [comment]
@xseman For my needs, I switched to https://github.com/cscott/lzma-purejs. It generates proper raw lzma. Only it adds some padding (additional information) to the end of file, but I just trimmed that and can extract with comnand line xz.

Also forked lzma-purejs, but basically I made it es6 module and reorganised some components, so it can be tree shaken.|
https://github.com/mauron85/lzma-purejs
